### ISSUE TITLE
how do I install this?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [kevin-cantwell/zlibr#4]
hello, complete non-programmer here. I wanna extract assets from a game and it looks like it is compressed with zlib, I found this and it looks like it could help me here. I don't know how to install this. I'm on windows 10. and I don't wanna switch to a whole new operating system just for some command line tool. so when I try to install it using the command you mention I just get this:

`# github.com/kevin-cantwell/zlib/cmd/zlib
go\src\github.com\kevin-cantwell\zlib\cmd\zlib\main.go:16:13: cannot use func literal (type func(*cli.Context)) as type cli.ActionFunc in assignment
go\src\github.com\kevin-cantwell\zlib\cmd\zlib\main.go:37:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)`

**Comment by kevin-cantwell** [comment]
Updated install methods. If you're on a newer version of Go, then

`go install github.com/kevin-cantwell/zlib/cmd/zlib@latest`

should work.

Or, you can download one of the release binaries, recently added:
https://github.com/kevin-cantwell/zlib/releases

Note, that I have not tested the linux or windows binaries, but there's a decent chance they'll work 🙃
